// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0M_qcHMvrm_Oc4Wa7HDv8b4XLRMPeaY4',
    appId: '1:579653692613:web:955bbb889b9a0fa2ce54ac',
    messagingSenderId: '579653692613',
    projectId: 'placar-ba25d',
    authDomain: 'placar-ba25d.firebaseapp.com',
    storageBucket: 'placar-ba25d.firebasestorage.app',
    measurementId: 'G-MZ6TZ94PBG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7r8Zo97GWfzBRUAgrq2dn8px1ouzOYdg',
    appId: '1:579653692613:android:e3e93bca31c3c37dce54ac',
    messagingSenderId: '579653692613',
    projectId: 'placar-ba25d',
    storageBucket: 'placar-ba25d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB53lxDmGogtrPjNfkuMe4TKtAHVWKmN2o',
    appId: '1:579653692613:ios:b29f6ea54316365dce54ac',
    messagingSenderId: '579653692613',
    projectId: 'placar-ba25d',
    storageBucket: 'placar-ba25d.firebasestorage.app',
    iosBundleId: 'com.lnascimento.handscores',
  );
}